---

- name: "install_node_js_14 and pm2"
  shell: |
    curl -sL https://deb.nodesource.com/setup_14.x | sudo -E bash -
    sudo apt install -y nodejs
    sudo npm install pm2 -g

- name: "create backend app directory"
  file:
    path: ~/backend-app
    state: directory

- name: "unarchive backend tar file"
  unarchive:
    src: ./files/artifact.tar.gz
    dest: ~/backend-app

- name: "install node dependancies"
  shell: |
    cd ~/backend-app
    npm i

- name: "execute node app with pm2"
  shell: |
    cd ~/backend-app/dist
    pm2 stop default
    pm2 start npm -- start

  register: execute_node

- name: print message
  debug:
    msg: "{{ execute_node.stdout_lines }}"
    
- name: "configure pm2 to work as a service"
  become: true
  shell: |
    env path=$path:/usr/local/bin pm2 startup systemd -u ubuntu --hp /home/ubuntu
